src/main/java/com/asolutworld/Authorization/beans/Login.java
package main.java.com.asolutworld.Authorization.beans;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import main.java.com.asolutworld.Authorization.dao.LoginDAO;
import main.java.com.asolutworld.Constants.Strings;

@ManagedBean
@SessionScoped
public class Login implements Serializable {

	private static final long serialVersionUID = 1094801825228386363L;
	
	private String pwd;
	private String msg;
	private String user;
	private String valid;
	private int u_id;
    private boolean isAdmin=false;

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

    public String getValid() {
        return valid;
    }

    public void setValid(String valid) {
        this.valid = valid;
    }

    public int getU_id() {
        return u_id;
    }

    public void setU_id(int u_id) {
        this.u_id = u_id;
    }

    //validate login

    public String validateUsernamePassword() {
		valid = LoginDAO.validate(user, pwd);
		if (valid.equals(Strings.ADMIN))isAdmin=true;
        else isAdmin=false;
		if (valid.equals(Strings.ADMIN)||valid.equals(Strings.USER)) {
			HttpSession session = SessionBean.getSession();
			session.setAttribute("u_id",LoginDAO.getU_ID());
            u_id=LoginDAO.getU_ID();

            session.setAttribute("username", user);
            session.setAttribute("role",valid);
			return "/faces/main";
		} else {
			FacesContext.getCurrentInstance().addMessage(
					null,
					new FacesMessage(FacesMessage.SEVERITY_WARN,
							"Incorrect Username and Passowrd",
							"Please enter correct username and Password"));
			return "index";
		}
	}

	//logout event, invalidate session
	public String logout() {
		HttpSession session = SessionBean.getSession();
		session.invalidate();
		return "index";
	}

	public boolean getIsLogin(){
		HttpSession session = SessionBean.getSession();
		if(session.getAttribute("u_id")==null)return false;
		else return true;
	}

    public boolean getIsAdmin(){
        return isAdmin;
    }
}

web/faces/comps/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:form>
    <p>
        Логин:
    </p>
    <h:inputText id="username" value="#{login.user}" />
    <h:message for="username"/>
    <p>
        Пароль:
    </p>
    <h:inputSecret id="password" value="#{login.pwd}" />
    <h:message for="password"/>
    <br/><br/>
    <h:commandButton id="loginButton" value="Вход" action="#{login.validateUsernamePassword}" />
    <h:commandButton value="Зарегистрироваться" action="register"/>
</h:form>
</html>

web/faces/comps/title.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <div class="titleBar">
        <h:form rendered="#{login.isLogin}">
            <h:commandButton value="Волонтеры" action="database"/>
            <h:commandButton value="Склады" action="main"/>
            <h:commandButton value="Запросы" action="requests"/>
            <h:commandButton value="Транспорт" action="transport"/>
            <h:commandButton value="Маршруты" action="ways"/>
            <h:commandButton value="Профиль" action="user">
                <f:param name="u_id" value="#{login.u_id}"/>
            </h:commandButton>
            <h:commandButton value="Выйти" action="#{login.logout}"/>
        </h:form>
    </div>
</f:view>
</html>